In [53]:
import pandas as pd 
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
np.random.seed(0)

In [39]:
%store -r data
%store -r train
%store -r test
%store -r y

# we can use the SciKit Learn's train_test_split function from model_selection 

In [42]:
# list of the feature column's names
features = data.columns[:18]
len(features)

18

In [43]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(18,), random_state=1)

In [44]:
clf.fit(train[features], y) 

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(18,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [45]:
clf.predict(test[features])

array([1, 1, 1, ..., 6, 6, 6])

In [46]:
# predicted probabilities of the first 10 rows
clf.predict_proba(test[features])[0:10]

array([[  9.97056051e-01,   2.30890655e-03,   7.13753649e-05,
          1.89788607e-04,   1.94662749e-04,   1.79215359e-04],
       [  9.96626353e-01,   2.64292940e-03,   7.94545711e-05,
          2.26065938e-04,   2.30994605e-04,   1.94202753e-04],
       [  9.96653455e-01,   2.61616982e-03,   7.97707161e-05,
          2.27476430e-04,   2.29071400e-04,   1.94056640e-04],
       [  9.96721963e-01,   2.58066686e-03,   7.68331164e-05,
          2.17876661e-04,   2.22424265e-04,   1.80235893e-04],
       [  9.97411078e-01,   2.03846882e-03,   6.14419603e-05,
          1.59720410e-04,   1.66103921e-04,   1.63187154e-04],
       [  9.96691068e-01,   2.58033045e-03,   7.69284365e-05,
          2.28246023e-04,   2.34141323e-04,   1.89285605e-04],
       [  9.96734180e-01,   2.56263390e-03,   7.72252907e-05,
          2.15558522e-04,   2.21217407e-04,   1.89184889e-04],
       [  9.96919613e-01,   2.40095888e-03,   7.23598801e-05,
          2.11739232e-04,   2.12520177e-04,   1.82809049e-04],


In [47]:
predictions = clf.predict(test[features])
predictions

array([1, 1, 1, ..., 6, 6, 6])

In [48]:
pd.crosstab(test['Activity'], predictions, rownames=['Actual Activity'], colnames=['Predicted Activity'])

Predicted Activity      1      2      3      4      5      6
Actual Activity                                             
1                   14905      1     10      0      0      0
2                       4  15026     64     94      0     27
3                      18     43  15004     14      0     19
4                       6     58     25  15046      7      0
5                       0      0      4      3  14693     20
6                       3     17      2     16     22  14829

In [ ]:
# use cross-validation for number of layers 

In [55]:
print(classification_report(test['Activity'],predictions))

             precision    recall  f1-score   support

          1       1.00      1.00      1.00     14916
          2       0.99      0.99      0.99     15215
          3       0.99      0.99      0.99     15098
          4       0.99      0.99      0.99     15142
          5       1.00      1.00      1.00     14720
          6       1.00      1.00      1.00     14889

avg / total       0.99      0.99      0.99     89980

