In [5]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt

# Load scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier

# Set random seed
np.random.seed(0)

In [1]:
%store -r data

In [2]:
data

RA_xacc   RA_yacc   RA_zacc  RA_xgyro  RA_ygyro  RA_zgyro  RA_xmag  \
0      -0.607840  1.390800  9.705600 -0.003695 -0.007452  0.001598 -0.33699   
1      -0.603140  1.449100  9.696100  0.014373  0.003043 -0.009156 -0.33723   
2      -0.613120  1.500000  9.684200 -0.000147 -0.000306  0.009623 -0.33727   
3      -0.605610  1.429700  9.679000  0.024193 -0.007612 -0.013744 -0.33686   
4      -0.608250  1.497600  9.676900  0.008742 -0.011820  0.007711 -0.33740   
5      -0.578570  1.410300  9.693700  0.016953 -0.007523 -0.004789 -0.33684   
6      -0.605740  1.483100  9.681700  0.009605 -0.014458  0.009467 -0.33657   
7      -0.593320  1.420000  9.683900  0.007173 -0.002239 -0.008239 -0.33691   
8      -0.596090  1.461100  9.679500  0.008617 -0.017934  0.013164 -0.33726   
9      -0.613180  1.468300  9.694000  0.010647  0.003174  0.002588 -0.33702   
10     -0.593610  1.458700  9.684400  0.005267  0.001420  0.002625 -0.33694   
11     -0.615620  1.444200  9.679300  0.006982 -0.002069  0.008810 -0.33673   
12     -0.603450  1.453900  9.669700 -0.003648 -0.000382 -0.002649 -0.33738   
13     -0.608310  1.468400  9.689200  0.023133 -0.003910  0.002448 -0.33611   
14     -0.608270  1.449000  9.684200 -0.005487 -0.011020 -0.006249 -0.33644   
15     -0.608390  1.483000  9.677100  0.033136 -0.003184 -0.014524 -0.33740   
16     -0.627950  1.490200  9.689100  0.002579 -0.002149 -0.000930 -0.33696   
17     -0.612960  1.405200  9.705900  0.008959 -0.002264 -0.012552 -0.33700   
18     -0.598520  1.478000  9.694100  0.014036 -0.012656  0.011372 -0.33700   
19     -0.598510  1.458700  9.684300  0.017857 -0.003994 -0.008179 -0.33643   
20     -0.603370  1.444100  9.684200  0.017750 -0.012787 -0.002893 -0.33720   
21     -0.618050  1.458600  9.693900  0.012581 -0.003202 -0.018805 -0.33634   
22     -0.598470  1.444100  9.684300  0.008916 -0.000432 -0.006310 -0.33693   
23     -0.615680  1.473200  9.684300  0.006154 -0.004811 -0.001864 -0.33609   
24     -0.608270  1.449000  9.684200  0.006175 -0.005718 -0.004538 -0.33787   
25     -0.603430  1.461100  9.679400  0.007176  0.000408 -0.011625 -0.33639   
26     -0.596100  1.463600  9.677100  0.019552 -0.011017 -0.002894 -0.33698   
27     -0.588690  1.449000  9.684300  0.001684 -0.005692 -0.002719 -0.33634   
28     -0.618170  1.473300  9.674600  0.005250 -0.003017  0.000820 -0.33617   
29     -0.615540  1.434400  9.693800  0.014303 -0.005803 -0.012611 -0.33547   
...          ...       ...       ...       ...       ...       ...      ...   
59970  20.169000  0.494120 -3.222400  0.731100  0.554820 -3.405600 -0.66170   
59971  11.175000 -1.092700 -2.647600 -0.477330  0.299220 -2.993600 -0.61043   
59972   4.445500 -0.706650 -2.338500 -1.144100  1.711600 -2.792300 -0.55666   
59973  -0.708100 -1.418500 -1.286300 -1.412900  1.561800 -2.984000 -0.61338   
59974  -0.191540 -0.641780 -0.431150 -1.194000  1.237800 -3.082900 -0.76289   
59975  -0.057379  0.011303  0.433680 -1.112000  1.277100 -2.787900 -0.91083   
59976   0.846380  3.567800 -0.253120 -1.043100  0.535130 -2.528500 -0.98284   
59977   1.036800  4.921200 -0.015552 -1.471400 -0.084625 -2.140100 -0.98910   
59978   1.124300  5.836100  0.233800  1.819500 -0.067989 -0.709780 -0.96213   
59979   5.284000  6.997100  0.097578  3.915100  0.010787  2.911900 -0.90404   
59980  16.161000  5.287800  0.342370  1.880100  0.240040  6.644300 -0.90903   
59981  17.228000  7.009000  1.403100  0.302620 -0.372310  7.320800 -0.91560   
59982  17.176000  1.877100  4.682700 -0.089496 -1.462400  6.803500 -0.89611   
59983  11.084000  1.060300  2.793900  0.464010 -3.724800  4.357100 -0.91451   
59984   2.951800  5.240100  2.080100  1.197500 -2.372800  2.349800 -0.85549   
59985   9.273200  5.800300  0.735700  1.194700 -1.826000  0.653770 -0.85528   
59986  15.428000  2.342700  3.459500  2.875200 -0.767940 -0.106800 -0.83678   
59987  31.940000  3.493700  0.723420  3.273900 -0.723930  0.837550 -0.80949   
59988  11.236000  5.316800  1.229000  1.009000 -1.552500  1

In [3]:
data.Activity.unique() #array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [7]:
# New Column 'isTrain' == True for a row if random number generated (between 0 and 1) is less than or equal to .75
# and false otherwise

data['is_train'] = np.random.uniform(0, 1, len(data)) <= .75
data.head()

RA_xacc  RA_yacc  RA_zacc  RA_xgyro  RA_ygyro  RA_zgyro  RA_xmag  RA_ymag  \
0 -0.60784   1.3908   9.7056 -0.003695 -0.007452  0.001598 -0.33699 -0.10005   
1 -0.60314   1.4491   9.6961  0.014373  0.003043 -0.009156 -0.33723 -0.10084   
2 -0.61312   1.5000   9.6842 -0.000147 -0.000306  0.009623 -0.33727 -0.10043   
3 -0.60561   1.4297   9.6790  0.024193 -0.007612 -0.013744 -0.33686 -0.09966   
4 -0.60825   1.4976   9.6769  0.008742 -0.011820  0.007711 -0.33740 -0.10030   

   RA_zmag  LA_xacc    ...     LA_ygyro  LA_zgyro   LA_xmag  LA_ymag  LA_zmag  \
0 -0.95706 -0.39088    ...     0.003125 -0.011263 -0.067876  0.79872 -0.21041   
1 -0.95680 -0.35910    ...     0.004322 -0.004176 -0.067793  0.79870 -0.20877   
2 -0.95746 -0.35433    ...    -0.006623 -0.007716 -0.067630  0.79884 -0.21053   
3 -0.95693 -0.36155    ...    -0.004702  0.001095 -0.066574  0.79853 -0.20959   
4 -0.95747 -0.36405    ...    -0.012473 -0.020107 -0.066845  0.79829 -0.20997   

   Subject  Activity  rowData  Frequence  is_train  
0        1         1        1          1      True  
1        1         1        2          2      True  
2        1         1        3          3      True  
3        1         1        4          4      True  
4        1         1        5          5      True  

[5 rows x 23 columns]

In [9]:
# 2 dataFrames: for Training and Testing
train, test = data[data['is_train']==True], data[data['is_train']==False]
print('Number of rows the training set:', len(train))
print('Number of rows in the test set:',len(test))

Number of observations in the training data: 270020
Number of observations in the test data: 89980


In [29]:
# list of the feature column's names
features = data.columns[:18]

features

Index(['RA_xacc', 'RA_yacc', 'RA_zacc', 'RA_xgyro', 'RA_ygyro', 'RA_zgyro',
       'RA_xmag', 'RA_ymag', 'RA_zmag', 'LA_xacc', 'LA_yacc', 'LA_zacc',
       'LA_xgyro', 'LA_ygyro', 'LA_zgyro', 'LA_xmag', 'LA_ymag', 'LA_zmag'],
      dtype='object')

In [34]:
#target
y = pd.factorize(train['Activity'])[0]+1

y

array([1, 1, 1, ..., 6, 6, 6])

In [35]:
# Create random forest Classifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)

# Train the Classifier to take the training features and learn how they relate
# to the training y (activities)
clf.fit(train[features], y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=2, oob_score=False, random_state=0,
            verbose=0, warm_start=False)

In [36]:
# Apply the Classifier we trained to the test data
clf.predict(test[features])

array([1, 1, 1, ..., 6, 6, 6])

In [37]:
# predicted probabilities of the first 10 rows
clf.predict_proba(test[features])[0:10]

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.]])

In [39]:
predictions = clf.predict(test[features])
predictions

array([1, 1, 1, ..., 6, 6, 6])

In [40]:
test['Activity'].head()

7     1
8     1
10    1
13    1
17    1
Name: Activity, dtype: int64

In [41]:
# Confusion matrix
pd.crosstab(test['Activity'], predictions, rownames=['Actual Activity'], colnames=['Predicted Activity'])

Predicted Activity      1      2      3      4      5      6
Actual Activity                                             
1                   14911      0      5      0      0      0
2                       0  15210      3      2      0      0
3                       0      2  15091      5      0      0
4                       0      6      3  15133      0      0
5                       0      2      2      0  14715      1
6                       0      0      0      1      1  14887

In [42]:
# List of the features and their importance scores
list(zip(train[features], clf.feature_importances_))

[('RA_xacc', 0.037605586691088648),
 ('RA_yacc', 0.067038783131325705),
 ('RA_zacc', 0.048890845712373884),
 ('RA_xgyro', 0.0010758749426464829),
 ('RA_ygyro', 0.005857574344025401),
 ('RA_zgyro', 0.0050328401238300567),
 ('RA_xmag', 0.13167061478426195),
 ('RA_ymag', 0.069240935757662797),
 ('RA_zmag', 0.032293003622593526),
 ('LA_xacc', 0.062957947249207627),
 ('LA_yacc', 0.054915913487286569),
 ('LA_zacc', 0.099116548961367387),
 ('LA_xgyro', 0.00076310691839094873),
 ('LA_ygyro', 0.001336653797114011),
 ('LA_zgyro', 0.0021655623895494554),
 ('LA_xmag', 0.094064141109173827),
 ('LA_ymag', 0.19065593407649023),
 ('LA_zmag', 0.095318132901611494)]